import './globals.css';

export const metadata = {
	title: 'Twitter clone 2.0',
	description: 'Generated by Next + Sanity',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}
